Synthetixio/staking

components/ProgressBar/ProgressBar.tsx, components/StatBox/StatBox.tsx, pages/staking/[[...action]].tsx
Also updated the progress bar's to use the correct border width and some box-shadow fixes.
=> Add c-ratio progress bar to staking page

containers/Connector/config.ts, package.json
**Background**
The Lattice1 is GridPlus' next generation Ethereum-focused programmable hardware wallet. It is an always-online device with physically separated secure compute and Linux general compute environments. For more information, see https://gridplus.io/
**About this PR**
This PR adds the Lattice1 as a wallet option for bnc-notify and bumps the Blocknative Onboard library version from v1.14.0 to v1.19.0. It also removes deprecated wallets no longer supported by the current version of the library (Dapper and Unilogin).
The Lattice1 can load smart contract ABIs so that interactions with your contracts are human-readable on the touchscreen which is drawn using the secure compute environment. This can help prevent man-in-the-middle attacks even when your computer is compromised. You …
=> Add Lattice1 Support and Bump BNC-Onboard to v1.19.0

components/Currency/CurrencyAmount/CurrencyAmount.tsx, sections/synths/AssetsTable.tsx
noticed that some USD values displayed on the /synths page had too many decimals and it was confusing me. dug a little deeper and realized it stemmed from the Currency.Amount component using the same currencyKey to determine how many decimals to use for both crypto and fiat amounts. updated Currency.Amount to accept an amountCurrencyKey and valueCurrencyKey and updated AssetsTable to provide the valueCurrencyKey separately
before:
after:
=> /synth page decimals fix

sections/layer2/deposit/DepositTab/DepositTab.tsx
Fixes #286 
Here's how it looks now:
The extra spacing caused this issue, I only modified it on the deposit page, so that other pages won't be affected (since the extra padding is actually needed)
=> fix(L2-Deposit): remove extra spacing on deposit SNX tab

sections/staking/components/TxSent/ActionCompleted.tsx
Fixes #296
Currently, the link goes to back `/earn` - need to clarify if this should go to https://www.curve.fi/susdv2/ instead?
=> fix(Minting): show correct APR for curve after a sucessful mint

queries/staking/helpers.ts, queries/staking/useSNXLockedValueQuery.ts
directly querying subgraph for holders
same as this https://github.com/Synthetixio/stats/commit/b1171bf3f1022d1fb38cc021ef55ab05493a835a
=> fix: NaN under SNX TVL on /earn

constants/queryKeys.ts, constants/routes.ts, hooks/useShortRewardsData.ts, queries/shorts/useSBTCShortsQuery.ts, queries/shorts/useSETHShortsQuery.ts, sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx, sections/earn/IncentivesMainnet.tsx, sections/earn/IncentivesTable.tsx, sections/earn/types.ts, translations/en.json
This feature branch adds the sETH shorting rewards to incentives "/earn".
Others
- Fixes the reference of the lpData via the index, made it reference instead the object so that adding more incentives would not mess up the index of the array.
- Disable 0% apy on the home layouts
=> Add sETH incentives and disable 0% apys

translations/en.json
Fix for wrong label shown on "Withdraw" page on L2.
=> chore: fix L2 withdraw SNX label

constants/nominations.json, queries/gov/useProposals.tsx, sections/gov/components/Proposal/Content.tsx, sections/gov/components/Proposal/Results.tsx
Since the council elections depend on a json that maps their addresses to their discord identity, there were some cases where if a invalid election was created, the proposals would not render correctly.
=> filter council nominations to exclude invalid proposals

components/Currency/CurrencyIcon/CurrencyIcon.tsx, hooks/useCryptoBalances.ts, queries/walletBalances/types.ts, sections/debt/components/PortfolioTable/PortfolioTable.tsx
Currently, a user's debt portfolio table will not have an entry for ETH-related assets if they do not have any sETH. This is also true for BTC-related assets and sBTC. This can be confusing since the assets presented would not add up to 100%. For example:
Currently:
This PR:
=> Show ETH/BTC balance even if user has no synths

queries/liquidityPools/useCurveSeuroPoolQuery.ts, queries/liquidityPools/useCurveSusdPoolQuery.ts, utils/web3.ts
temp fix for issue where ethers instances of curve gauges contracts is returning weird "out of gas" error on some calls. probably won't work if user is connected to a none-web3 provider.
=> fix: workaround for stats load issue on ethers curve gauges contracts

components/Currency/CurrencyIcon/CurrencyIcon.tsx, components/ProgressBar/ProgressBar.tsx, constants/currency.ts, constants/links.ts, constants/queryKeys.ts, queries/1inch/use1InchQuoteQuery.ts, queries/1inch/use1InchSwapQuery.ts, queries/tokenLists/types.ts, queries/tokenLists/useSynthetixTokenList.ts, queries/tokenLists/useZapperTokenList.ts, sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx, sections/earn/IncentivesDefault.tsx, sections/earn/IncentivesMainnet.tsx, sections/earn/IncentivesTable.tsx, sections/earn/LPTab/LPTab.tsx, sections/earn/LPTab/RewardsBox/RewardsBox.tsx, sections/earn/LPTab/StakeTab/StakeTab.tsx, sections/earn/types.ts
This PR aims to:
- Convert currency icon to use tokenlists and synthetix/assets as a fallback so that we can automatically get the latest currency assets deployed
- Adds the balancer incentives to the frontpage layout
- Disables 1inch queries on L2
- Fixes the progress bar when the timer has ended on incentives (makes it full rainbow width)
=> Refactor Staking dApp 

sections/gov/components/Create/index.tsx
Remove decimals on proposals start and end timestamps, Snapshot hub now will reject proposals with decimals on timestamps.
=> Remove decimals on proposal start & end timestamps

sections/staking/components/BurnTab/BurnTab.tsx, translations/en.json
- adds error state for not enough ETH in wallet
- also changes burn amount to === all sUSD in wallet (which is debtBalance + 1inch buffer) to account for possible debt shifts
=> fix: Clear Debt

queries/escrow/useEscrowDataQuery.tsx
Escrow screen is broken on L2 because `TotalPendingMigration()` doesn't exist.
=> set TotalPendingMigration to 0 if L2

components/StatsSection/StatsSection.tsx, hooks/useHistoricalDebtData.ts, queries/rates/useHistoricalRatesQuery.ts, queries/synths/useSynthsTotalSupplyQuery.ts, sections/debt/components/DebtPieChart/DebtPieChart.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Wrapper.tsx, sections/shared/Layout/SideNav/DesktopSideNav.tsx
Fixes the shown sETH value to not include sETH issued by [EthWrapper](https://sips.synthetix.io/sips/sip-112) because the later is not part of the debt pool.
QA Task:
- Go to https://staking-git-fix-global-debt-pool-stat-synthetixio.vercel.app/debt
- Ensure the global debt pool pie chart matches the one at https://stats.synthetix.io/
=> fix: EthWrapper sETH is not part of the debt pool

hooks/useUserStakingData.ts, queries/debt/useGetDebtDataQuery.ts, sections/earn/ClaimTab/ClaimTab.tsx, sections/staking/hooks/useStakingCalculations.ts
- Added a check in order to know if current c-ratio is below target c-ratio (`targetThreshold` also taken into account)
- Small refactoring in the claim screen as the `burn sUSD` button was disabled (and it shouldn't)
=> check if cratio is below target

components/Currency/CurrencyIcon/CurrencyIcon.tsx
Bug causing zapper and 1inch options to not be attempted.
=> fix: tokenlists regression

components/BufferSelector/BufferSelector.tsx, components/BufferSelector/index.ts, components/GasSelector/GasSelector.tsx, constants/defaults.ts, sections/staking/components/BurnTab/BurnTab.tsx, sections/staking/components/StakingInfo/BurnInfo.tsx, sections/staking/components/StakingInfo/InfoLayout.tsx, sections/staking/components/StakingInfo/MintInfo.tsx, sections/staking/components/StakingInput/StakingInput.tsx, translations/en.json
Fixes https://github.com/synthetixio/issues/issues/190
To test
1) Mint max
2) Try to burnMax (input should be blocked if you choose a slippage > 0, unless you have spare sUSD)
3) Acquire more sUSD
4) Try to burn with buffer, if successful it should burn only the debt YOU have and not more
Other notes
- Should allow for 0% buffer burning max
=> [Feature]: Add a selectable buffer when trying to burn max debt on Staking dApp

sections/earn/ClaimTab/ClaimTab.tsx
Notes: On L2 the claim errors were all showing an ambiguous error "Internal JSON RPC error" this is because the error object is different to the one on L1
=> Fix the claim errors on L2 not showing

queries/liquidityPools/useYearnSNXVaultQuery.ts
- Use https://api.yearn.finance/v1/chains/1/vaults/all for vault data, see this PR on yearn.fi repo: https://github.com/antonnell/yearn-finance/pull/61
- Add extra null checks for `tvl` and `net_apy` values
=> Fix api endpoint and null checks for yearn stats

queries/liquidityPools/useYearnSNXVaultQuery.ts, sections/earn/IncentivesMainnet.tsx
Currently, the displayed staked balance on the `earn` page is inaccurate (it shows wallet SNX balance), this PR corrects that
=> Fix staked balance for Yearn SNX Vault

sections/earn/ClaimTab/ClaimAndCloseFeeButton.tsx, sections/earn/ClaimTab/ClaimTab.tsx
Voting is not blocked on a contract level. And since voting is done on L1 I think it's fairly confusing to require voting on L2.
We also seem to have a bug that require users to reload after voting and going back to L2, this change should mean that users doesn't run in to this.
=> Dont require voting on L2

components/Input/NumericInput.tsx, sections/loans/components/ActionBox/BorrowSynthsTab/AssetInput.tsx
Without this change you cant remove a an accidentally wrong value without special tricks. This feature makes the input work more how you expect an input to work. 
I didn't change it everywhere since Numeric input is used in a lot of places.
=> Allow empty flag numeric input

constants/defaults.ts, containers/Loans/Loans.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Close.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Deposit.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Draw.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Repay.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Withdraw.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/helpers.test.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/helpers.ts, sections/loans/components/ActionBox/BorrowSynthsTab/AssetInput.tsx, sections/loans/components/ActionBox/BorrowSynthsTab/BorrowSynthsTab.tsx, sections/loans/components/ActionBox/components/CRatio.tsx, sections/loans/constants.ts, translations/en.json
- User safe cratio buffer rather than hardcoded safe c-ratio
Fix Draw screen 
- Prevent user from adding more than max draw.
- Disable if you're below safe c-cratio
- Max button  now adds max debt to safe c-ratio (150%)
=> Loans draw and cratio improvements

sections/escrow/components/RewardEscrowSchedule/RewardEscrowSchedule.tsx
This fixes a bug where the vesting schedule table keeps reseting to the first page
Image from bug report:
=> Dont auto reset pagination

sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Deposit.tsx, sections/loans/components/ActionBox/BorrowSynthsTab/BorrowSynthsTab.tsx
renBTC has 8 decimals and we had some mistakes regarding that.
I dont really have a way to test this yet. 
Trying to sort that out
=> Fix renBBTC loans

sections/shared/Layout/SideNav/DesktopSideNav.tsx, translations/en.json
I was confused about this number, and I believe more users could feel the same. Adding some clarity would help I believe.
This PR fixes that.
=> [FEAT] Desktop sidebar: show tooltip info about total SNX staked

components/StatsSection/StatsSection.tsx, constants/defaults.ts, pages/_app.tsx, sections/shared/Layout/SideNav/DesktopSideNav.tsx
This PR adds three performance improvements
1. Change refetch interval to 5 min instead of every 30 sec.
Queries will still update as you navigate around, we could even consider disable this
2. We dont need to refetch everytime the user focus the window
Making all queries refetch every time the window refocus is putting a lot of load on the app.
Instead of having this as a default for att queries it should be used specifically for queries that want this.
Most of the time I dont think it's needed since the data will update when user navigates around
3.  When calculating the 7day rate change use the end of hour price 7 days ago
The `sevenDaysAgoSeconds` gets passed to `subgraph.useGetRateUpdates`
The subgraph hooks pass all arguments as query keys. This meant we were constantly rerendering …
=> Perf updates

pages/_app.tsx, pages/loans/[[...action]].tsx
The loans page requires quite a lot of data when loading. When the `unstated` provider is mounted it triggers all the `useEffect`s in `container/Loans` to fire off. With this change we only let that happen when a user visits the Loans page
=> Only load loans data while on the loans page

sections/delegate/DelegateForm.tsx, sections/delegate/DelegateTable.tsx, sections/delegate/ToggleDelegateApproval.tsx, translations/en.json
When changing permission or adding a new delegate wallet it doesn't show up on the table.
The reason for this is cause the table's data is fetch from a subgraph and the subgraph doesn't have time to get synced.
I try to resolve this in two ways. 
- `sleep` for 5s before quering the subgraph
-  Add refresh button with a tooltip explanation why a refresh is required
=> Delegate action

constants/routes.ts, hooks/useLiquidationRewards.ts, pages/earn/[[...pool]].tsx, sections/earn/Incentives.tsx, sections/earn/IncentivesDefault.tsx, sections/earn/IncentivesMainnet.tsx, sections/earn/IncentivesTable.tsx, sections/earn/LiquidationTab/LiquidationTab.tsx, sections/earn/LiquidationTab/index.ts, sections/earn/types.ts, translations/en.json
UI for claiming liquidation rewards. 
Very similar to the claim tab but calling the `Liquidation.getReward` instead. 
Should work in delegated mode. Does not require you do have be below C-Ratio threshold
**Mainnet:**
**Optimism:**
=> Liquidation rewards

package.json, sections/dashboard/PossibleActions/Layouts/LayoutDelegate.tsx, sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx, sections/dashboard/PossibleActions/Layouts/LayoutLayerTwo.tsx, sections/dashboard/PossibleActions/Layouts/getSynthetixRewardTile.test.tsx, sections/dashboard/PossibleActions/Layouts/getSynthetixRewardTile.tsx, test-setup/svgMock.js, translations/en.json, yarn.lock
Make the claim rewards tile on the landing page a bit smarter.
See `getSynthetixRewardTile.test.tsx` for logic.
Also fixed some bugs for when in delegate mode.
=> Staking reward tile

sections/earn/LiquidationTab/LiquidationTab.tsx
- Make sure total value show the rewards in USD
- Dont refetch the query until the user clicks dismiss so that we show "claimed" correctly
Bug report:
=> Liquidation rewards fix

hooks/useLiquidationAmountToFixCollateral.ts, pages/staking/SelfLiquidation.tsx, utils/formatters/number.ts
- If SNXRate is 0 we're loading
- Dont enable selfLiquidate call is c-ration is 0
- Dont render self liq ui is user not staking
- Dont try to estimate amount to fix collateral is debtbalance is 0
- Is zero should not convert to number incase there's overflow
=> Self liq fixes

hooks/useLPData.ts, queries/liquidityPools/useCurveSusdPoolQuery.ts, sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx, sections/dashboard/PossibleActions/Layouts/LayoutLayerTwo.tsx, sections/earn/IncentivesDefault.tsx, sections/earn/IncentivesMainnet.tsx, sections/earn/IncentivesTable.tsx
- Update `curveSusdPoolQuery` to support optimism and use API when available. This makes the results more similiar to what we see on curve.fu
- Make sure we display curve data for both optimism and mainnet, both on the landing page and on the /earn page.
- Optimism also had the G-UNI pool removed
Landing page optimism:
Landing page mainnet:
Earn page mainnet:
Earn page optimism
=> Curve apys

containers/Connector/config.ts
Can be enabled once this is merged:
https://github.com/blocknative/web3-onboard/pull/1165
=> Disable trezor module for now
