sections/earn/ClaimTab/ClaimTab.tsx
=> fix proportion of snx logos and add effects

constants/links.ts, sections/layer2/index.tsx, sections/staking/hooks/useStakingCalculations.ts, translations/en.json
* change migrate logic
* fix UI text and link
=> change migrate logic (#256)

.babelrc
=> chore: dont add qa props on dev builds

constants/routes.ts, hooks/useHistoricalDebtData.ts, package-lock.json, package.json, pages/debt.tsx, queries/debt/useGetDebtSnapshotQuery.ts, sections/debt/DebtChart/DebtChart.tsx, sections/debt/DebtChart/index.tsx, sections/shared/Layout/constants.ts, styles/theme/colors.ts, translations/en.json
My proposed port of the debt tracker from mintr. Tried to mirror the existing design components as much as possible. 
Thinking this `/debt` page can be used to implement 2. and 3. from #305 as well.
=> Debt Tracker Implementation

package-lock.json, package.json, utils/network.ts
=> fix: deprecate `window.web3` and use `@metamask/detect-provider` for provider detection

sections/shared/modals/WalletOptionsModal/WalletOptionsModal.tsx
=> fix(WalletOptionsModal): match spacing of stop watching/disconnect to design

constants/date.ts, sections/earn/IncentivesTable.tsx, sections/shared/Layout/SideNav/PeriodBarStats.tsx, translations/en.json
=> refactor(Timer): Switch to a more human readable format

pages/debt.tsx, queries/synths/useSynthsTotalSupplyQuery.ts, queries/walletBalances/useRenBTCBalanceQuery.ts, queries/walletBalances/useWBTCBalanceQuery.ts, queries/walletBalances/useWETHBalanceQuery.ts, sections/debt/components/DebtPieChart/DebtPieChart.tsx, sections/debt/components/PortfolioTable/PortfolioTable.tsx
@clementbalestrat @evgenyboxer this PR addresses the comments from https://github.com/Synthetixio/staking/pull/355, let me know if I missed anything!
=> useMemo for expensive values, move contracts out of query

queries/liquidityPools/useCurveSeuroPoolQuery.ts, queries/liquidityPools/useCurveSusdPoolQuery.ts
=> fix: updated apy endpoint for curve.fi

package-lock.json, package.json
=> deps: update @synthetixio/js to 2.39.3

mutations/gov/useSignMessage.ts, package-lock.json, queries/gov/useProposal.ts, queries/gov/useProposals.tsx, sections/gov/components/Proposal/DilutionContent.tsx, sections/gov/components/Proposal/History.tsx, sections/gov/components/helper.ts, sections/gov/hooks/useCouncilMembers.ts
Fixes the issue where the update in the snapshot strategy does not match ```.toLowerCase()``` to addresses anymore and instead uses the ethers util ```ethers.utils.getAddress() // checksum check``` instead that is more reliable and consistent
=> use checksum everywhere instead of lowercase (branched from master)

sections/layer2/index.tsx
Pretty depressing to see 0% APR... so here's a hotfix for this. (merge to master).
Before:
After:
=> hotfix: hardcode L2 weekly rewards to show correct APR

package-lock.json, package.json
Context:
https://discord.com/channels/413890591840272394/809129093605097554/827060886731489370
=> fix: proper L2 urls for block explorer and icons 

package-lock.json, package.json
* fix: updated optimism-networks with support for proper block explorer and icon urls
* fix: lockfile
* fix: new version with proper build
* fix: new version with https
=> fix: proper L2 urls for block explorer and icons  (#459) release

sections/layer2/index.tsx, sections/shared/Layout/AppLayout.tsx, store/wallet/index.ts
This reverts commit e67b7a93e5fbe82c0b37282485242938cfd67e37.
=> Revert "disable deposits on L2 and freeze L2 (#466)"

sections/layer2/withdraw/InfoBox/InfoBox.tsx, translations/en.json
https://discord.com/channels/413890591840272394/809129093605097554/830273005518716969
=> feat: info about missing withdrawals

sections/earn/ClaimTab/ClaimTab.tsx, translations/en.json
- Mintr L2 allows users to close fee period which isn't supported in Staking yet.
- This PR adds a "close fee period" button in the `earn` page when network is L2 and period can be closed.
=> added close fee period button

assets/svg/app/close.svg, constants/storage.ts, sections/shared/Layout/Banner/Banner.tsx, sections/shared/Layout/Banner/index.ts, sections/shared/Layout/Header.tsx, translations/en.json
=> Warning banner

containers/Loans/Loans.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Wrapper.tsx, sections/loans/components/ActionBox/BorrowSynthsTab/BorrowSynthsTab.tsx, sections/loans/components/ActionBox/BorrowSynthsTab/FormButton.tsx, sections/loans/components/ActionBox/components/CRatio.tsx, sections/loans/components/ActionBox/components/InfoSVG.tsx, sections/loans/components/ActionBox/components/LoanCRatio.tsx, sections/loans/constants.ts, translations/en.json
- fix hardcoded min loan cratio
- catch insufficient collateral amount error
=> improvement: loans post-release fixes

queries/liquidityPools/useCurveSeuroPoolQuery.ts, queries/liquidityPools/useCurveSusdPoolQuery.ts, utils/web3.ts
https://github.com/ethers-io/ethers.js/issues/1474#issuecomment-820844166
=> fix: gas issue on some read calls due to the berlin upgrade

.github/workflows/audit_build_verify.yml
https://github.com/Synthetixio/issues/issues/60
=> ci: invalidate cloudfront cache on release

.github/workflows/audit_build_verify.yml, components/Currency/CurrencyIcon/CurrencyIcon.tsx, components/ProgressBar/ProgressBar.tsx, constants/currency.ts, constants/links.ts, constants/queryKeys.ts, package-lock.json, package.json, queries/1inch/use1InchQuoteQuery.ts, queries/1inch/use1InchSwapQuery.ts, queries/tokenLists/types.ts, queries/tokenLists/useSynthetixTokenList.ts, queries/tokenLists/useZapperTokenList.ts, sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx, sections/earn/ClaimTab/ClaimTab.tsx, sections/earn/IncentivesDefault.tsx, sections/earn/IncentivesMainnet.tsx, sections/earn/IncentivesTable.tsx, sections/earn/LPTab/LPTab.tsx, sections/earn/LPTab/RewardsBox/RewardsBox.tsx, sections/earn/LPTab/StakeTab/StakeTab.tsx, sections/earn/types.ts
Reverts Synthetixio/staking#509
=> Revert "Revert "dev => master""

.github/workflows/audit_build_verify.yml, components/Currency/CurrencyIcon/CurrencyIcon.tsx, components/ProgressBar/ProgressBar.tsx, constants/currency.ts, constants/links.ts, constants/queryKeys.ts, package-lock.json, package.json, queries/1inch/use1InchQuoteQuery.ts, queries/1inch/use1InchSwapQuery.ts, queries/tokenLists/types.ts, queries/tokenLists/useSynthetixTokenList.ts, queries/tokenLists/useZapperTokenList.ts, sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx, sections/earn/ClaimTab/ClaimTab.tsx, sections/earn/IncentivesDefault.tsx, sections/earn/IncentivesMainnet.tsx, sections/earn/IncentivesTable.tsx, sections/earn/LPTab/LPTab.tsx, sections/earn/LPTab/RewardsBox/RewardsBox.tsx, sections/earn/LPTab/StakeTab/StakeTab.tsx, sections/earn/types.ts
Reverts Synthetixio/staking#511
=> Revert "Revert "Revert "Revert "dev => master""""

.github/workflows/audit_build_verify.yml, vercel.json
The issue was related to `Cache-Control` header which wasn't provided correct value by default, so now it has to be explicitly specified inside `vercel.json` config file.
https://github.com/Synthetixio/issues/issues/60
=> fix: caching issues on index file

sections/dashboard/PossibleActions/Layouts/LayoutLayerOne.tsx
=> fix: sCoin incentives text

package-lock.json, package.json
=> dev => master

vercel.json
part of https://github.com/Synthetixio/issues/issues/60
=> fix: improve cache-control & vary headers

sections/staking/components/BurnTab/BurnTab.tsx
Reverts Synthetixio/staking#546
=> Revert "dev => master"

components/PieChart/PieChart.tsx, queries/synths/useSynthsTotalSupplyQuery.ts, sections/debt/components/DebtPieChart/DebtPieChart.tsx, sections/debt/components/DebtPoolTable/DebtPoolTable.tsx, translations/en.json
fixes https://github.com/Synthetixio/issues/issues/203
=> fix: global debt pool share compute

constants/nominations.json, sections/shared/Layout/AppLayout.tsx, translations/en.json
NOTE: in the process of refactoring out the latest election query since we have all three running at the same time now
=> update nominations json + bring back notification banner

sections/layer2/index.tsx, sections/shared/SystemStatus/SystemStatus.tsx
This reverts commit 2387932ff325215e99ec8579b7e9375da87b9ec0.
=> Revert "chore: L2 maintenance for regenesis (#588)"

constants/queryKeys.ts, queries/deposits/useGetDepositsDataQuery.ts, queries/deposits/useGetDepositsIsActiveQuery.ts, queries/withdrawals/useGetWithdrawalsDataQuery.ts, queries/withdrawals/useGetWithdrawalsIsActiveQuery.ts, sections/layer2/index.tsx, sections/layer2/withdraw/WithdrawTab/TabContent.tsx, sections/layer2/withdraw/WithdrawTab/WithdrawTab.tsx, sections/shared/Layout/AppLayout.tsx, translations/en.json
Adds support for `initiationActive` from our bridge contracts to enable/disable deposits/withdrawals
fixes https://github.com/Synthetixio/issues/issues/222
=> feat: disable Deposits/Withdrawals depending on bridge contracts

contracts/councilDilution.js, queries/gov/useProposalQuery.ts
Fix for https://sips.synthetix.io/sips/sip-152
=> update council dilution contract

queries/network/useEthGasPriceQuery.ts
This reverts commit 8f2c783fd5c49c0a0ce82611265c23013d601fe0.
=> Revert "set gas price to 0 if on ovm main-net"

queries/network/useEthGasPriceQuery.ts, translations/en.json
Just reverts @andytcf hardcoded price fix from last month
=> dev -> master

pages/_app.tsx
adds matomo tracking code to staking app
=> add matomo

sections/staking/hooks/useClearDebtCalculations.ts
this will prevent sandwhiching
=> [hotfix] Fix 1inch slippage

.github/workflows/audit_build_verify.yml, sections/layer2/migrate/MigrateTab/MigrateTab.tsx
there were 2 issues:
* all wei data must be mapped to BN before sending in txn
* claimable amount was a wei so it must be compared `.gt(0)`
=> fix migration page crashes and incorrect data

pages/_document.tsx
there are 2 matomo script injections in this app. Only one needed is in `_app`.
=> remove document matomo

sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Deposit.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Wrapper.tsx, sections/staking/hooks/useStakingCalculations.ts, utils/transactions.ts
we have to either deprecate or get this code fully migrated to useTxn functions soon
=> fix Deposit page not correctly handling value sent for eth loans

package.json
=> fix: deploy as ssg, trigger export after build

amplify.yml, customHttp.yml
Does not affect current deployments from vercel in any way.
=> amplify: add initial configuration

customHttp.yml, next.config.js, vercel.json
=> cherrypick header changes from dev

constants/links.ts, sections/shared/SystemStatus/SystemStatus.tsx
app will check its hostname, and it will only show the maintenance page notice if its the prod deployment
=> only show maintenance page on prod deployment

containers/Loans/Loans.tsx
- erc20LoanContract doesn't exists on l2
- contract function interactionDelay does not exists on l2
- Make sure all number are wei rather than a mix of bignumber / wei
=> Make sure we load interest rate, issueFeeRate and interaction delay correcly

sections/debt/components/DebtPieChart/DebtPieChart.tsx, translations/en.json, utils/formatters/number.ts
- added the suggested skewValueChart key from @bachstatter 
- updated the sorting function
- added missing key in translation object
=> fixing proportion of pie chart

containers/Connector/Connector.tsx
Also updated the secrets in the vercel dahsboard. Couldn't validate if the infura id was corect cause it was a secret. Saved it now as plain text.
=> Remove commented out infura id

containers/Connector/Connector.tsx, package.json, sections/shared/Layout/UserMenu/UserMenu.tsx, store/wallet/index.ts, yarn.lock
- Shows ens avatar only if the user is already set. For users with no avatar, it won't be displayed.
No libraries installed.
=> Ens avatar support

constants/links.ts, constants/queryKeys.ts, sections/staking/components/StakingInfo/InfoLayout.tsx, sections/staking/components/StakingInfo/MintInfo.tsx, translations/en.json
=> Fetch and display minStakeTime

sections/staking/components/MintTab/MintTab.tsx
=> Only enable mint tx when we have amountToMint

sections/staking/components/StakingInput/StakingInput.tsx
Instead it will be cleared when user changes the amount
=> Amount to large should not be clearable

sections/debt/components/DebtPieChart/DebtPieChart.tsx, sections/debt/components/DebtPieChart/debt-pool-data.ts, sections/debt/components/DebtPieChart/pie-data.ts, sections/debt/components/DebtPoolTable/DebtPoolTable.tsx, sections/debt/components/DebtTabs/index.tsx, translations/en.json
This implements #1013, we still might want to refine the messaging.
=> Percentage to hedge

constants/NotificationContainer.tsx, hooks/isMounted.ts, hooks/useUserStakingData.ts, sections/shared/Layout/SideNav/DesktopSubMenu.tsx
Fixes `Warning: Expected server HTML to contain a matching <div> in <div>` and ` Error: invalid address or ENS name (argument="name", value=null...`
=> Fix errors in console

.github/workflows/updateDependency.yml
Make sure the update deps workflow use yarn
=> Update dependency workflow should use yarn

constants/links.ts
=> Link to new optimism bridge

sections/debt/components/DebtPoolTable/DebtPoolTable.tsx, translations/en.json
Make hedging information clearer
=> Improve hedging instructions

sections/staking/components/StakingInfo/InfoLayout.tsx, sections/staking/components/StakingInfo/MintInfo.tsx, translations/en.json
=> Liq warning based on data

pages/staking/SelfLiquidation.tsx, pages/staking/[[...action]].tsx, sections/shared/modals/TxConfirmationModal/TxConfirmationModal.tsx, translations/en.json
On the staking page, is a wallet have been flag, show big warning and option to self liquidate
=> Self liquidation

pages/gov/[[...panel]].tsx
- Also remove the unneccesary setTitle ( use use the <Head//>)
=> Show new elections container permantently

containers/UI/UI.tsx, pages/debt.tsx, pages/delegate.tsx, pages/earn/[[...pool]].tsx, pages/escrow/[[...action]].tsx, pages/gov/[[...panel]].tsx, pages/history.tsx, pages/index.tsx, pages/l2/index.tsx, pages/l2/migrate.tsx, pages/synths.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/LoanList.tsx, sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/index.tsx, sections/loans/components/ActionBox/BorrowSynthsTab/BorrowSynthsTab.tsx, sections/shared/Layout/Header.tsx, sections/shared/helpers/index.ts, sections/staking/components/BurnTab/BurnTab.tsx, sections/staking/components/MintTab/MintTab.tsx, translations/en.json
This PR removes logic for setting the Header title and subtitle state. Title/subtitle are to be replaced by derived values from the nav state.
=> Remove headerTitle, subTitle from context

components/KwentaBanner/KwentaBanner.tsx, constants/links.ts
Create kwentaTrading link
Point trading banner to kwenta.io/trading
=> update kwenta trading link
